"""create subscriptions table and enrichments.notified_at

Revision ID: 332db5cf139e
Revises: cf6467e36f9d
Create Date: 2026-08-10 01:08:45.077946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '332db5cf139e'
down_revision: Union[str, Sequence[str], None] = 'cf6467e36f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('ministry_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'ministry_id', name='uq_subscriptions_chat_ministry')
    )
    op.create_index(op.f('ix_subscriptions_chat_id'), 'subscriptions', ['chat_id'], unique=False)
    op.add_column('enrichments', sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrichments', 'notified_at')
    op.drop_index(op.f('ix_subscriptions_chat_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
