"""create ministries and articles tables

Revision ID: ca37f51d9726
Revises: 
Create Date: 2026-08-09 22:23:37.563613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca37f51d9726'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ministries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prid', sa.Integer(), nullable=False),
    sa.Column('ministry_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('pib_office', sa.String(length=100), nullable=True),
    sa.Column('release_datetime', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prid', name='uq_articles_prid')
    )
    op.create_index('ix_articles_ministry_release', 'articles', ['ministry_id', 'release_datetime'], unique=False)
    op.create_index(op.f('ix_articles_prid'), 'articles', ['prid'], unique=False)
    op.create_index(op.f('ix_articles_release_datetime'), 'articles', ['release_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_release_datetime'), table_name='articles')
    op.drop_index(op.f('ix_articles_prid'), table_name='articles')
    op.drop_index('ix_articles_ministry_release', table_name='articles')
    op.drop_table('articles')
    op.drop_table('ministries')
    # ### end Alembic commands ###
